version: '2'
services:
  zookeeper:
    image: confluent/zookeeper
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"
    network_mode: "host"
  kafka:
    image: confluent/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "localhost:2181"
#      KAFKA_ADVERTISED_HOST_NAME: "192.168.99.100" (mac docker-machine ip)
      KAFKA_BROKER_ID: 0
    network_mode: "host"
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    network_mode: "host"
  hadoop:
    build: hadoop/
    ports:
      - "9000:9000"
      - "50075:50075"
      - "50070:50070"
    network_mode: "host"
